### ISSUE TITLE
请问这是我的设置问题吗

### ISSUE THREAD

**Issue by jiahao2333** [tianqiraf/DouZero_For_HappyDouDiZhu#1]
我首先按照要求安装了所需依赖，进入对局点击开始后提示输出

等待下家出牌
等待下家出牌
等待下家出牌

下家出牌： 44333
Traceback (most recent call last):
  File "c:\Users\11984\Downloads\DouZero_For_HappyDouDiZhu-master\main.py", line 170, in init_cards    self.start()
  File "c:\Users\11984\Downloads\DouZero_For_HappyDouDiZhu-master\main.py", line 226, in start     
    self.env.step(self.user_position, self.other_played_cards_env)
TypeError: step() takes 1 positional argument but 3 were given

以上这样的报错
图形界面卡死，图片附上

![report](https://user-images.githubusercontent.com/53189564/126132022-ea2a3de0-a973-4b4d-8a92-6db4fd9ef067.PNG)

**Comment by jiahao2333** [comment]
屏幕分辨率1920X1080 缩放125%

**Comment by jiahao2333** [comment]
当我是地主时，报错是这样的
{'three_landlord_cards': [14, 9, 6], 'landlord': [30, 20, 17, 17, 17, 14, 14, 13, 12, 11, 11, 10, 10, 9, 8, 8, 7, 6, 5, 5], 'landlord_down': [3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 6, 6, 6, 7, 7, 7, 8], 'landlord_up': [8, 9, 9, 9, 10, 10, 11, 11, 12, 12, 12, 13, 13, 13, 14, 14, 17]}
开始出牌

Traceback (most recent call last):
  File "c:\Users\11984\Downloads\DouZero_For_HappyDouDiZhu-master\main.py", line 170, in init_cards    self.start()
  File "c:\Users\11984\Downloads\DouZero_For_HappyDouDiZhu-master\main.py", line 179, in start     
    action_message = self.env.step(self.user_position)
TypeError: step() takes 1 positional argument but 2 were given

**Comment by tianqiraf** [comment]
@jiahao2333 你是在修改源码吗，检查/douzero/env/game.py的step()函数是否接收三个参数

**Comment by jiahao2333** [comment]
> @jiahao2333你是在修改源码吗，检查/douzero/env/game.py的step()函数是否接收到参数

emmm我并没有修改源码，但是出现了这个问题

**Comment by whenjonny** [comment]
好奇他这个算法，不区分牌型吗？黑桃，方片这些
