### ISSUE TITLE
1.0/2.0都闪退

### ISSUE THREAD

**Issue by laulguo** [tianqiraf/DouZero_For_HappyDouDiZhu#2]
配置环境
torch==1.7.1
GitPython==3.0.5
gitdb2==2.0.6
PyAutoGUI==0.9.50
PyQt5==5.15.4
PyQt5-sip==12.8.1
rlcard
sip
opencv

**Comment by tianqiraf** [comment]
@laulguo 能否贴上报错信息

**Comment by QIN2DIM** [comment]
我也遇到了同样的情况，控制台没有打印任何信息，窗口消失，程序结束运行=。=不过也不算“闪退”，是点了`开始`后，几秒后自动退出了。

**Comment by QIN2DIM** [comment]
![image](https://user-images.githubusercontent.com/62018067/126184035-87c7c700-6ca8-40ef-ac15-ec7d6e0ef984.png)
如果你是直接运行`main.py`秒退的话不会打印错误信息，但如果你是在`Terminal`里编译项目的话，出现了以上的错误，请使用`pip install opencv-python`安装依赖。

`

**Comment by laulguo** [comment]
> 
> 
> @laulguo 能否贴上报错信息

Traceback (most recent call last):
  File "D:\DouZero_For_HappyDouDiZhu-2.0\main.py", line 115, in init_cards
    self.user_hand_cards_real = self.find_my_cards(self.MyHandCardsPos)
  File "D:\DouZero_For_HappyDouDiZhu-2.0\main.py", line 290, in find_my_cards
    img = pyautogui.screenshot(region=pos)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\pyscreeze\__init__.py", line 143, in wrapper
    raise PyScreezeException('The Pillow package is required to use this function.')
pyscreeze.PyScreezeException: The Pillow package is required to use this function.
报错信息是这个

**Comment by tianqiraf** [comment]
@laulguo  安装Pillow
