### ISSUE TITLE
文件丢失报错

### ISSUE THREAD

**Issue by RayKx** [tianqiraf/DouZero_For_HappyDouDiZhu#6]
Traceback (most recent call last):
  File "C:\Users\A\Desktop\DouZero_For_HappyDouDiZhu-master\DouZero_For_HappyDouDiZhu-master\main.py", line 115, in init_cards
    self.user_hand_cards_real = self.find_my_cards(self.MyHandCardsPos)
  File "C:\Users\A\Desktop\DouZero_For_HappyDouDiZhu-master\DouZero_For_HappyDouDiZhu-master\main.py", line 295, in find_my_cards
    user_hand_cards_real += card[1] * self.cards_filter(list(result), self.MyFilter)
  File "D:\ProgramData\Anaconda3\lib\site-packages\pyscreeze\__init__.py", line 206, in _locateAll_opencv
    needleImage = _load_cv2(needleImage, grayscale)
  File "D:\ProgramData\Anaconda3\lib\site-packages\pyscreeze\__init__.py", line 169, in _load_cv2
    raise IOError("Failed to read %s because file is missing, "
OSError: Failed to read pics/mrD.png because file is missing, has improper permissions, or is an unsupported or invalid format

**Comment by RayKx** [comment]
检查了一下文件夹，这个mrD.png是J，文件是存在的

**Comment by RayKx** [comment]
运行main.py后 弹出的gui为全黑，仅显示开始和停止两个按钮

**Comment by flagtim** [comment]
Traceback (most recent call last):
  File "E:\DouZero\DouZero_For_HappyDouDiZhu\main.py", line 115, in init_cards
    self.user_hand_cards_real = self.find_my_cards(self.MyHandCardsPos)
  File "E:\DouZero\DouZero_For_HappyDouDiZhu\main.py", line 295, in find_my_cards
    user_hand_cards_real += card[1] * self.cards_filter(list(result), self.MyFilter)
  File "D:\Python3.8.6\lib\site-packages\pyscreeze\__init__.py", line 206, in _locateAll_opencv
    needleImage = _load_cv2(needleImage, grayscale)
  File "D:\Python3.8.6\lib\site-packages\pyscreeze\__init__.py", line 169, in _load_cv2
    raise IOError("Failed to read %s because file is missing, "
OSError: Failed to read pics/mrD.png because file is missing, has improper permissions, or is an unsupported or invalid format

**Comment by flagtim** [comment]
> 运行main.py后 弹出的gui为全黑，仅显示开始和停止两个按钮
我也出现了此种情况，请问你解决了吗

**Comment by RayKx** [comment]
> > 运行main.py后 弹出的gui为全黑，仅显示开始和停止两个按钮
> > 我也出现了此种情况，请问你解决了吗

我们的问题似乎一样，但目前并没有解决
